[2024-01-27 13:48:20,838: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 13:48:20,838: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 13:48:20,838: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 13:48:20,846: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-27 13:48:20,846: INFO: common: created directory at: artifacts]
[2024-01-27 13:48:20,846: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 13:48:22,617: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 2618:24E7D2:39D812:413D17:65B4BC56
Accept-Ranges: bytes
Date: Sat, 27 Jan 2024 08:18:30 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4742-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1706343510.383806,VS0,VE350
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6129e1af28ada4f022843d2ae762fc9f264db014
Expires: Sat, 27 Jan 2024 08:23:30 GMT
Source-Age: 0

]
[2024-01-27 13:48:22,647: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 12:12:15,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:12:15,111: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:12:15,115: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:12:15,117: INFO: common: created directory at: artifacts]
[2024-01-28 12:12:15,120: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 12:12:46,613: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:12:46,615: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:12:46,617: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:12:46,619: INFO: common: created directory at: artifacts]
[2024-01-28 12:12:46,620: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 12:16:36,602: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:16:36,604: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:16:36,607: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:16:36,609: INFO: common: created directory at: artifacts]
[2024-01-28 12:16:36,610: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 12:17:23,484: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-28 12:17:23,484: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:17:23,498: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:17:23,498: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:17:23,498: INFO: common: created directory at: artifacts]
[2024-01-28 12:17:23,498: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-28 12:17:24,861: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1EA6:244126:56B941:62316C:65B5F883
Accept-Ranges: bytes
Date: Sun, 28 Jan 2024 06:47:33 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4739-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1706424453.851381,VS0,VE326
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 62ab242b664c64a82b6be9f12a0892d01aa2caa9
Expires: Sun, 28 Jan 2024 06:52:33 GMT
Source-Age: 0

]
[2024-01-28 12:17:24,881: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 12:17:39,325: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:17:39,327: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:17:39,332: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:17:39,333: INFO: common: created directory at: artifacts]
[2024-01-28 12:17:39,333: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 12:20:39,757: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:20:39,759: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:20:39,763: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:20:39,764: INFO: common: created directory at: artifacts]
[2024-01-28 12:20:39,766: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 12:21:04,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:21:04,876: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:21:04,879: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:21:04,880: INFO: common: created directory at: artifacts]
[2024-01-28 12:21:04,881: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 12:24:21,163: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:24:21,165: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:24:21,166: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:24:21,171: INFO: common: created directory at: artifacts]
[2024-01-28 12:24:21,171: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 12:41:28,897: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-28 12:41:28,897: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:41:28,897: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:41:28,897: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:41:28,897: INFO: common: created directory at: artifacts]
[2024-01-28 12:41:28,897: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-28 12:41:30,254: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1EA6:244126:56B941:62316C:65B5F883
Accept-Ranges: bytes
Date: Sun, 28 Jan 2024 07:11:38 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4723-BOM
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1706425898.231894,VS0,VE314
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1050ffe2af4127fcbf1bcba5ad39582a5986cdcc
Expires: Sun, 28 Jan 2024 07:16:38 GMT
Source-Age: 0

]
[2024-01-28 12:41:30,285: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 12:41:30,285: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-28 12:41:30,285: ERROR: main: DataValiadtionPipeline.main() takes 0 positional arguments but 1 was given]
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 22, in <module>
    data_ingestion.main()
TypeError: DataValiadtionPipeline.main() takes 0 positional arguments but 1 was given
[2024-01-28 12:42:37,221: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-28 12:42:37,224: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:42:37,224: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:42:37,228: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:42:37,228: INFO: common: created directory at: artifacts]
[2024-01-28 12:42:37,230: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-28 12:42:37,230: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-28 12:42:37,233: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 12:42:37,233: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-28 12:42:37,233: ERROR: main: DataValiadtionPipeline.main() takes 0 positional arguments but 1 was given]
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 22, in <module>
    data_validation.main()
TypeError: DataValiadtionPipeline.main() takes 0 positional arguments but 1 was given
[2024-01-28 12:46:16,318: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-28 12:46:16,318: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:46:16,318: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:46:16,334: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:46:16,334: INFO: common: created directory at: artifacts]
[2024-01-28 12:46:16,334: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-28 12:46:16,336: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-28 12:46:16,336: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 12:46:16,336: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-28 12:46:16,342: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 12:46:16,342: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 12:46:16,346: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 12:46:16,346: INFO: common: created directory at: artifacts]
[2024-01-28 12:46:16,346: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 12:46:16,374: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-28 14:50:37,976: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 14:50:37,976: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 14:50:37,985: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 14:50:37,985: INFO: common: created directory at: artifacts]
[2024-01-28 14:50:37,985: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 14:51:59,175: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 14:51:59,177: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 14:51:59,179: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 14:51:59,179: INFO: common: created directory at: artifacts]
[2024-01-28 14:51:59,179: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 14:52:03,775: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 14:52:03,777: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 14:52:03,782: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 14:52:03,784: INFO: common: created directory at: artifacts]
[2024-01-28 14:52:03,784: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 14:52:47,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 14:52:47,154: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 14:52:47,161: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 14:52:47,165: INFO: common: created directory at: artifacts]
[2024-01-28 14:52:47,166: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 14:54:40,557: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 14:54:40,559: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 14:54:40,562: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 14:54:40,564: INFO: common: created directory at: artifacts]
[2024-01-28 14:54:40,565: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 14:56:19,219: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 14:56:19,222: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 14:56:19,226: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 14:56:19,228: INFO: common: created directory at: artifacts]
[2024-01-28 14:56:19,229: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 14:56:31,496: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 14:56:31,497: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 14:56:31,500: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 14:56:31,501: INFO: common: created directory at: artifacts]
[2024-01-28 14:56:31,505: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 15:15:11,118: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-28 15:15:11,121: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 15:15:11,123: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 15:15:11,131: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 15:15:11,135: INFO: common: created directory at: artifacts]
[2024-01-28 15:15:11,135: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-28 15:15:14,105: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FDEE:14FDB3:57BBF7:62B5C7:65B6222E
Accept-Ranges: bytes
Date: Sun, 28 Jan 2024 09:45:22 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4722-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1706435122.921679,VS0,VE321
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 5e601112120043cb2d24faebca1cb2c07f09d288
Expires: Sun, 28 Jan 2024 09:50:22 GMT
Source-Age: 0

]
[2024-01-28 15:15:14,122: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 15:15:14,125: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-28 15:15:14,125: ERROR: main: name 'DataValiadtionPipeline' is not defined]
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 21, in <module>
    data_validation = DataValiadtionPipeline()
                      ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'DataValiadtionPipeline' is not defined
[2024-01-28 15:16:49,923: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-28 15:16:49,926: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 15:16:49,926: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 15:16:49,930: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 15:16:49,930: INFO: common: created directory at: artifacts]
[2024-01-28 15:16:49,931: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-28 15:16:49,932: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-28 15:16:49,933: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 15:16:49,933: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-28 15:16:49,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 15:16:49,940: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 15:16:49,943: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 15:16:49,943: INFO: common: created directory at: artifacts]
[2024-01-28 15:16:49,943: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 15:16:49,972: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-28 15:16:49,972: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-28 15:16:49,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 15:16:49,983: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 15:16:49,988: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 15:16:49,988: INFO: common: created directory at: artifacts]
[2024-01-28 15:16:49,988: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 15:16:50,004: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-28 15:21:08,177: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-28 15:21:08,177: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 15:21:08,177: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 15:21:08,177: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 15:21:08,177: INFO: common: created directory at: artifacts]
[2024-01-28 15:21:08,177: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-28 15:21:08,177: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-28 15:21:08,189: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 15:21:08,189: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-28 15:21:08,189: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 15:21:08,189: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 15:21:08,197: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 15:21:08,200: INFO: common: created directory at: artifacts]
[2024-01-28 15:21:08,200: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 15:21:08,221: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-28 15:21:08,221: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-28 15:21:08,221: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 15:21:08,221: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 15:21:08,221: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 15:21:08,236: INFO: common: created directory at: artifacts]
[2024-01-28 15:21:08,236: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 15:21:08,269: INFO: data_transformation: Splited data into training and test sets]
[2024-01-28 15:21:08,269: INFO: data_transformation: (1199, 12)]
[2024-01-28 15:21:08,269: INFO: data_transformation: (400, 12)]
[2024-01-28 15:21:08,269: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-28 16:11:05,082: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:11:05,095: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:11:05,095: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:11:05,095: INFO: common: created directory at: artifacts]
[2024-01-28 16:11:32,883: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:11:32,889: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:11:32,892: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:11:32,892: INFO: common: created directory at: artifacts]
[2024-01-28 16:13:00,938: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:13:00,940: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:13:00,943: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:13:00,945: INFO: common: created directory at: artifacts]
[2024-01-28 16:15:53,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:15:53,887: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:15:53,890: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:15:53,891: INFO: common: created directory at: artifacts]
[2024-01-28 16:22:32,711: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:22:32,713: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:22:32,717: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:22:32,720: INFO: common: created directory at: artifacts]
[2024-01-28 16:24:33,030: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:24:33,033: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:24:33,035: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:24:33,037: INFO: common: created directory at: artifacts]
[2024-01-28 16:24:33,038: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-28 16:32:55,358: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-28 16:32:55,364: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:32:55,364: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:32:55,364: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:32:55,364: INFO: common: created directory at: artifacts]
[2024-01-28 16:32:55,364: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-28 16:32:55,364: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-28 16:32:55,373: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-28 16:32:55,373: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-28 16:32:55,373: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:32:55,373: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:32:55,373: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:32:55,373: INFO: common: created directory at: artifacts]
[2024-01-28 16:32:55,373: INFO: common: created directory at: artifacts/data_validation]
[2024-01-28 16:32:55,402: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-28 16:32:55,402: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-28 16:32:55,407: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:32:55,407: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:32:55,411: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:32:55,411: INFO: common: created directory at: artifacts]
[2024-01-28 16:32:55,411: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-28 16:32:55,432: INFO: data_transformation: Splited data into training and test sets]
[2024-01-28 16:32:55,439: INFO: data_transformation: (1199, 12)]
[2024-01-28 16:32:55,439: INFO: data_transformation: (400, 12)]
[2024-01-28 16:32:55,439: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-28 16:32:55,439: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-28 16:32:55,443: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-28 16:32:55,443: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-28 16:32:55,445: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-28 16:32:55,445: INFO: common: created directory at: artifacts]
[2024-01-28 16:32:55,448: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-28 16:32:55,499: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 11:48:13,817: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:48:13,828: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:48:13,842: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:48:13,842: INFO: common: created directory at: artifacts]
[2024-01-29 11:48:13,846: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:48:18,163: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:48:18,167: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:48:18,170: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:48:18,171: INFO: common: created directory at: artifacts]
[2024-01-29 11:48:18,174: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:48:27,940: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:48:27,942: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:48:27,947: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:48:27,948: INFO: common: created directory at: artifacts]
[2024-01-29 11:48:27,948: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:49:21,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:49:21,144: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:49:21,147: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:49:21,148: INFO: common: created directory at: artifacts]
[2024-01-29 11:49:21,150: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:49:47,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:49:47,246: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:49:47,249: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:49:47,251: INFO: common: created directory at: artifacts]
[2024-01-29 11:49:47,251: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:53:22,620: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:53:22,623: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:53:22,626: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:53:22,628: INFO: common: created directory at: artifacts]
[2024-01-29 11:53:22,628: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:53:44,672: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:53:44,674: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:53:44,677: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:53:44,678: INFO: common: created directory at: artifacts]
[2024-01-29 11:53:44,680: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:54:24,684: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:54:24,687: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:54:24,689: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:54:24,691: INFO: common: created directory at: artifacts]
[2024-01-29 11:54:24,691: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:55:44,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:55:44,419: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:55:44,422: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:55:44,423: INFO: common: created directory at: artifacts]
[2024-01-29 11:55:44,424: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:56:24,244: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 11:56:24,247: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 11:56:24,250: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 11:56:24,250: INFO: common: created directory at: artifacts]
[2024-01-29 11:56:24,252: INFO: common: created directory at: artifacts/model_evalution]
[2024-01-29 11:56:24,267: INFO: common: json file saved at: artifacts\model_evalution\metrics.json]
[2024-01-29 12:06:26,606: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:06:26,619: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:06:26,619: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:06:26,619: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:06:26,619: INFO: common: created directory at: artifacts]
[2024-01-29 12:06:26,619: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:06:30,568: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 2F82:3B5ED0:2267A2:268C3A:65B73CBA
Accept-Ranges: bytes
Date: Mon, 29 Jan 2024 06:36:38 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4737-BOM
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1706510198.026005,VS0,VE241
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 996287517cd594af8627b0e8f3e160bd48040a91
Expires: Mon, 29 Jan 2024 06:41:38 GMT
Source-Age: 0

]
[2024-01-29 12:06:30,593: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:06:30,593: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:06:30,593: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:06:30,599: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:06:30,599: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:06:30,599: INFO: common: created directory at: artifacts]
[2024-01-29 12:06:30,599: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:06:30,648: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:06:30,648: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:06:30,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:06:30,673: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:06:30,674: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:06:30,674: INFO: common: created directory at: artifacts]
[2024-01-29 12:06:30,674: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:06:30,711: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:06:30,711: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:06:30,711: INFO: data_transformation: (400, 12)]
[2024-01-29 12:06:30,711: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:06:30,711: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:06:30,714: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:06:30,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:06:30,719: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:06:30,720: INFO: common: created directory at: artifacts]
[2024-01-29 12:06:30,720: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:06:30,812: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:06:30,812: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:06:30,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:06:30,813: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:06:30,819: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:06:30,820: INFO: common: created directory at: artifacts]
[2024-01-29 12:06:30,821: ERROR: main: "'ConfigBox' object has no attribute 'model_evalution'"]
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'model_evalution'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'model_evalution'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'model_evalution'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'model_evalution'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'model_evalution'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'model_evalution'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'model_evalution'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 57, in <module>
    model_evalution.main()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\pipeline\stage_05_model_evalution.py", line 16, in main
    model_evalution_config = config.get_model_evalution_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\config\configuration.py", line 82, in get_model_evalution_config
    config= self.config.model_evalution
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'model_evalution'"
[2024-01-29 12:07:35,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:07:35,800: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:07:35,803: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:07:35,804: INFO: common: created directory at: artifacts]
[2024-01-29 12:08:43,645: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:08:43,660: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:08:43,660: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:08:43,660: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:08:43,660: INFO: common: created directory at: artifacts]
[2024-01-29 12:08:43,660: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:08:43,660: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-29 12:08:43,676: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:08:43,676: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:08:43,676: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:08:43,676: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:08:43,676: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:08:43,676: INFO: common: created directory at: artifacts]
[2024-01-29 12:08:43,676: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:08:43,702: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:08:43,702: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:08:43,714: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:08:43,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:08:43,714: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:08:43,714: INFO: common: created directory at: artifacts]
[2024-01-29 12:08:43,714: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:08:43,747: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:08:43,747: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:08:43,747: INFO: data_transformation: (400, 12)]
[2024-01-29 12:08:43,750: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:08:43,750: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:08:43,750: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:08:43,750: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:08:43,750: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:08:43,750: INFO: common: created directory at: artifacts]
[2024-01-29 12:08:43,750: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:08:43,797: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:08:43,797: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:08:43,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:08:43,814: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:08:43,814: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:08:43,814: INFO: common: created directory at: artifacts]
[2024-01-29 12:08:43,818: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-29 12:08:43,818: ERROR: main: "'ConfigBox' object has no attribute 'metrics_file_name'"]
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'metrics_file_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'metrics_file_name'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'metrics_file_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'metrics_file_name'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'metrics_file_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'metrics_file_name'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'metrics_file_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 57, in <module>
    model_evalution.main()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\pipeline\stage_05_model_evalution.py", line 16, in main
    model_evalution_config = config.get_model_evalution_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\config\configuration.py", line 92, in get_model_evalution_config
    metrics_file_name=config.metrics_file_name,
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'metrics_file_name'"
[2024-01-29 12:12:31,972: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:12:31,984: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:12:31,984: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:12:31,984: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:12:31,984: INFO: common: created directory at: artifacts]
[2024-01-29 12:12:31,984: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:12:31,984: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-29 12:12:31,984: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:12:31,984: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:12:31,984: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:12:31,984: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:12:31,984: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:12:32,000: INFO: common: created directory at: artifacts]
[2024-01-29 12:12:32,000: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:12:32,023: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:12:32,023: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:12:32,023: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:12:32,023: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:12:32,030: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:12:32,030: INFO: common: created directory at: artifacts]
[2024-01-29 12:12:32,030: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:12:32,056: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:12:32,056: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:12:32,059: INFO: data_transformation: (400, 12)]
[2024-01-29 12:12:32,059: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:12:32,059: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:12:32,061: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:12:32,061: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:12:32,066: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:12:32,068: INFO: common: created directory at: artifacts]
[2024-01-29 12:12:32,068: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:12:32,106: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:12:32,106: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:12:32,109: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:12:32,109: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:12:32,114: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:12:32,114: INFO: common: created directory at: artifacts]
[2024-01-29 12:12:32,114: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-29 12:12:32,133: ERROR: main: 'ModelEvalutionConfig' object has no attribute 'metrics_file_name']
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 57, in <module>
    model_evalution.main()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\pipeline\stage_05_model_evalution.py", line 18, in main
    model_evalution_config.save_results()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\components\model_evalution.py", line 32, in save_results
    save_json(path=Path(self.config.metrics_file_name),data=scores)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelEvalutionConfig' object has no attribute 'metrics_file_name'
[2024-01-29 12:14:05,660: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:14:05,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:14:05,675: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:14:05,681: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:14:05,682: INFO: common: created directory at: artifacts]
[2024-01-29 12:14:05,682: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:14:05,682: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-29 12:14:05,684: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:14:05,684: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:14:05,693: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:14:05,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:14:05,695: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:14:05,695: INFO: common: created directory at: artifacts]
[2024-01-29 12:14:05,701: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:14:05,726: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:14:05,726: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:14:05,730: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:14:05,730: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:14:05,730: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:14:05,730: INFO: common: created directory at: artifacts]
[2024-01-29 12:14:05,730: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:14:05,753: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:14:05,753: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:14:05,765: INFO: data_transformation: (400, 12)]
[2024-01-29 12:14:05,765: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:14:05,767: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:14:05,768: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:14:05,768: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:14:05,774: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:14:05,774: INFO: common: created directory at: artifacts]
[2024-01-29 12:14:05,774: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:14:05,818: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:14:05,818: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:14:05,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:14:05,821: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:14:05,825: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:14:05,827: INFO: common: created directory at: artifacts]
[2024-01-29 12:14:05,827: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-29 12:14:05,830: ERROR: main: 102]
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 57, in <module>
    model_evalution.main()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\pipeline\stage_05_model_evalution.py", line 18, in main
    model_evalution_config.save_results()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\components\model_evalution.py", line 22, in save_results
    model = joblib.load(self.config.model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\joblib\numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\joblib\numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\AppData\Local\Programs\Python\Python311\Lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
    ~~~~~~~~^^^^^^^^
KeyError: 102
[2024-01-29 12:16:27,372: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:16:27,389: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:16:27,389: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:16:27,399: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:16:27,399: INFO: common: created directory at: artifacts]
[2024-01-29 12:16:27,399: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:16:27,402: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-29 12:16:27,405: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:16:27,405: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:16:27,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:16:27,410: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:16:27,413: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:16:27,413: INFO: common: created directory at: artifacts]
[2024-01-29 12:16:27,416: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:16:27,438: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:16:27,438: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:16:27,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:16:27,449: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:16:27,451: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:16:27,451: INFO: common: created directory at: artifacts]
[2024-01-29 12:16:27,454: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:16:27,478: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:16:27,478: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:16:27,478: INFO: data_transformation: (400, 12)]
[2024-01-29 12:16:27,478: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:16:27,481: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:16:27,481: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:16:27,481: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:16:27,487: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:16:27,487: INFO: common: created directory at: artifacts]
[2024-01-29 12:16:27,487: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:16:27,525: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:16:27,525: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:16:27,530: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:16:27,531: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:16:27,534: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:16:27,534: INFO: common: created directory at: artifacts]
[2024-01-29 12:16:27,534: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-29 12:16:27,537: ERROR: main: 102]
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 57, in <module>
    model_evalution.main()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\pipeline\stage_05_model_evalution.py", line 18, in main
    model_evalution_config.save_results()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\components\model_evalution.py", line 22, in save_results
    model = joblib.load(filename=self.config.model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\joblib\numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\joblib\numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\AppData\Local\Programs\Python\Python311\Lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
    ~~~~~~~~^^^^^^^^
KeyError: 102
[2024-01-29 12:24:25,408: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:24:25,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:24:25,427: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:24:25,430: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:24:25,430: INFO: common: created directory at: artifacts]
[2024-01-29 12:24:25,432: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:24:25,433: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-29 12:24:25,436: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:24:25,436: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:24:25,436: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:24:25,436: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:24:25,443: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:24:25,443: INFO: common: created directory at: artifacts]
[2024-01-29 12:24:25,443: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:24:25,470: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:24:25,470: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:24:25,473: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:24:25,478: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:24:25,480: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:24:25,480: INFO: common: created directory at: artifacts]
[2024-01-29 12:24:25,480: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:24:25,505: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:24:25,507: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:24:25,507: INFO: data_transformation: (400, 12)]
[2024-01-29 12:24:25,508: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:24:25,508: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:24:25,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:24:25,511: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:24:25,516: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:24:25,516: INFO: common: created directory at: artifacts]
[2024-01-29 12:24:25,519: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:24:25,557: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:24:25,560: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:24:25,562: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:24:25,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:24:25,566: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:24:25,566: INFO: common: created directory at: artifacts]
[2024-01-29 12:24:25,566: ERROR: main: 'ConfigurationManager' object has no attribute 'get_model_evalution_config']
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 57, in <module>
    model_evalution.main()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\pipeline\stage_05_model_evaluation.py", line 16, in main
    model_evalution_config = config.get_model_evalution_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_model_evalution_config'
[2024-01-29 12:25:14,996: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:25:14,996: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:14,996: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:15,011: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:15,011: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:15,011: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:25:15,011: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-29 12:25:15,011: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:25:15,011: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:25:15,025: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:15,025: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:15,025: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:15,025: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:15,025: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:25:15,053: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:25:15,053: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:25:15,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:15,058: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:15,064: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:15,064: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:15,064: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:25:15,088: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:25:15,088: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:25:15,088: INFO: data_transformation: (400, 12)]
[2024-01-29 12:25:15,088: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:25:15,088: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:25:15,092: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:15,095: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:15,097: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:15,097: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:15,097: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:25:15,142: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:25:15,142: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:25:15,148: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:15,149: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:15,152: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:15,152: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:15,152: ERROR: main: "'ConfigBox' object has no attribute 'model_evaluation'"]
Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'model_evaluation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'model_evaluation'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'model_evaluation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'model_evaluation'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'model_evaluation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'model_evaluation'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'model_evaluation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\main.py", line 57, in <module>
    model_evaluation.main()
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\pipeline\stage_05_model_evaluation.py", line 16, in main
    model_evaluation_config = config.get_model_evaluation_config()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\krish goyani\desktop\ds projects\bappy\src\ML_Project\config\configuration.py", line 81, in get_model_evaluation_config
    config = self.config.model_evaluation
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Krish Goyani\Desktop\DS Projects\Bappy\env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'model_evaluation'"
[2024-01-29 12:25:46,857: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:25:46,858: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:46,863: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:46,865: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:46,866: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:46,866: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:25:46,866: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-29 12:25:46,869: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:25:46,869: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:25:46,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:46,874: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:46,880: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:46,880: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:46,882: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:25:46,906: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:25:46,906: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:25:46,915: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:46,915: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:46,918: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:46,919: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:46,920: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:25:46,940: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:25:46,947: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:25:46,947: INFO: data_transformation: (400, 12)]
[2024-01-29 12:25:46,947: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:25:46,947: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:25:46,950: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:46,950: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:46,955: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:46,955: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:46,956: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:25:46,992: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:25:46,992: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:25:46,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:25:46,999: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:25:47,001: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:25:47,001: INFO: common: created directory at: artifacts]
[2024-01-29 12:25:47,002: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-29 12:25:47,024: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2024-01-29 12:25:47,024: INFO: main: >>>>>> stage Model Evalution Stage completed <<<<<<

x==========x]
[2024-01-29 12:26:28,993: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 12:26:29,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:26:29,010: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:26:29,014: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:26:29,015: INFO: common: created directory at: artifacts]
[2024-01-29 12:26:29,017: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 12:26:31,359: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 2F82:3B5ED0:2267A2:268C3A:65B73CBA
Accept-Ranges: bytes
Date: Mon, 29 Jan 2024 06:56:40 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4721-BOM
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1706511400.853950,VS0,VE340
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 392a149d83b517ec6257e4573b1d63f5e77a5c80
Expires: Mon, 29 Jan 2024 07:01:40 GMT
Source-Age: 0

]
[2024-01-29 12:26:31,377: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 12:26:31,377: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 12:26:31,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:26:31,377: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:26:31,385: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:26:31,385: INFO: common: created directory at: artifacts]
[2024-01-29 12:26:31,385: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 12:26:31,405: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 12:26:31,409: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 12:26:31,418: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:26:31,418: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:26:31,424: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:26:31,424: INFO: common: created directory at: artifacts]
[2024-01-29 12:26:31,439: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 12:26:31,466: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 12:26:31,468: INFO: data_transformation: (1199, 12)]
[2024-01-29 12:26:31,468: INFO: data_transformation: (400, 12)]
[2024-01-29 12:26:31,469: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 12:26:31,470: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 12:26:31,471: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:26:31,471: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:26:31,475: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:26:31,475: INFO: common: created directory at: artifacts]
[2024-01-29 12:26:31,477: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 12:26:31,523: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 12:26:31,523: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 12:26:31,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 12:26:31,527: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 12:26:31,531: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 12:26:31,531: INFO: common: created directory at: artifacts]
[2024-01-29 12:26:31,531: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-29 12:26:31,554: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2024-01-29 12:26:31,554: INFO: main: >>>>>> stage Model Evalution Stage completed <<<<<<

x==========x]
[2024-01-29 13:52:06,076: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-29 13:52:06,092: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 13:52:06,092: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 13:52:06,108: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 13:52:06,108: INFO: common: created directory at: artifacts]
[2024-01-29 13:52:06,108: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-29 13:52:06,108: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-01-29 13:52:06,124: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-29 13:52:06,124: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-01-29 13:52:06,132: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 13:52:06,132: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 13:52:06,139: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 13:52:06,139: INFO: common: created directory at: artifacts]
[2024-01-29 13:52:06,139: INFO: common: created directory at: artifacts/data_validation]
[2024-01-29 13:52:06,171: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-01-29 13:52:06,171: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-01-29 13:52:06,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 13:52:06,187: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 13:52:06,190: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 13:52:06,190: INFO: common: created directory at: artifacts]
[2024-01-29 13:52:06,190: INFO: common: created directory at: artifacts/data_transformation]
[2024-01-29 13:52:06,222: INFO: data_transformation: Splited data into training and test sets]
[2024-01-29 13:52:06,222: INFO: data_transformation: (1199, 12)]
[2024-01-29 13:52:06,222: INFO: data_transformation: (400, 12)]
[2024-01-29 13:52:06,222: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-01-29 13:52:06,222: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-01-29 13:52:06,228: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 13:52:06,228: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 13:52:06,232: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 13:52:06,234: INFO: common: created directory at: artifacts]
[2024-01-29 13:52:06,234: INFO: common: created directory at: artifacts/model_trainer]
[2024-01-29 13:52:06,282: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x]
[2024-01-29 13:52:06,282: INFO: main: >>>>>> stage Model Evalution Stage started <<<<<<]
[2024-01-29 13:52:06,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-29 13:52:06,291: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-29 13:52:06,294: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-29 13:52:06,294: INFO: common: created directory at: artifacts]
[2024-01-29 13:52:06,294: INFO: common: created directory at: artifacts/model_evaluation]
[2024-01-29 13:52:06,319: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2024-01-29 13:52:06,319: INFO: main: >>>>>> stage Model Evalution Stage completed <<<<<<

x==========x]
